### ISSUE TITLE
java.lang.NoSuchFieldException: foodLevel

### ISSUE THREAD

**Issue by jburrows82** [ArcAios26/supersaturation#4] opened 2022-07-10 03:36 UTC
Minecraft 1.18.2
Forge 40.1.60

Crash while just exploring.

[Crashlog](https://gist.github.com/jburrows82/3bb69d75457668c29b2e31d25e62e163)

[latest](https://gist.github.com/jburrows82/4c48302434ac23c1cb4c444f3a83e42e)

[debug](https://gist.github.com/jburrows82/55e4775cbafbe3188b1e6bd6ee441688)

**Comment by ArcAios26** [comment] 2022-07-10 07:17
Fixed in latest commit # cfaebddabed409b4ea848476df9a57c9050f1697
Problem caused by the conversion to official mappings when porting up to 1.17 and 1.18 stripping the obfuscated name out of the Reflection code. 
Fix has been committed for 1.18 and 1.17 and builds for both versions are being uploaded to curseforge.
note: 1.16 code is getting a fix since it was where the mapping conversion took place but a new build is unnecessary as a new build was never published with the bug.

**Closed as completed by ArcAios26** 2022-07-10 07:17 UTC
